### ISSUE TITLE
NLCD legend always appears

### ISSUE THREAD

**Issue by Castronova** [CUAHSI/HydroClient#2]
The NLCD legend appears under the Legends tab when the USGS LandCover 2011 layer is deselected. It should only be displayed when the landcover layer is displayed on the map.

![image](https://cloud.githubusercontent.com/assets/4822372/19861100/afb4eb94-9f61-11e6-8938-3e0ab8d4d773.png)

**Comment by ANightCoder-Brian** [comment]
30-Nov-2016 - Fixed

Added logic to initially hide the legend and conditionally show the legend only when then LandCover map layer is displayed
